name: GitHub Action

on:
  push:
    branches: [master]

jobs:
  build-push-images:
    name: Budowa i publikacja obrazu z zadania 2 na repozytorium
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          tags: |
            s99175/zadanie2:v1
            ghcr.io/rafal-okuniewski/zadanie2:v1

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-test
          environment_name: dockertest-env
          existing_bucket_name: elasticbeanstalk-us-east-2-XXXXXXXXXX
          version_label: "docker-app-${{ steps.format-time.outputs.replaced }}"
          region: us-east-2
          deployment_package: deploy.zip

          